FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Command to run the application using Gunicorn with Uvicorn workers
# Gunicorn for production-ready server, Uvicorn as the ASGI server
CMD gunicorn app:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT